# Generated by Django 5.2.10 on 2026-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0, verbose_name='No')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='Hostname')),
                ('db', models.CharField(blank=True, max_length=200, verbose_name='DB Name')),
                ('database_status', models.CharField(blank=True, max_length=100, verbose_name='Database Status')),
                ('ip_oam', models.CharField(blank=True, max_length=50, verbose_name='IP OAM')),
                ('ip_service', models.CharField(blank=True, max_length=50, verbose_name='IP Service')),
                ('category_database', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('port', models.CharField(blank=True, max_length=20, verbose_name='Port')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Version')),
                ('installation_date', models.CharField(blank=True, max_length=50, verbose_name='Installation Date')),
                ('operating_system', models.TextField(blank=True, verbose_name='Operating System')),
                ('apps', models.CharField(blank=True, max_length=300, verbose_name='Apps')),
                ('apps_on_product_catalog', models.CharField(blank=True, max_length=200, verbose_name='Apps on Product Catalog')),
                ('business_category', models.CharField(blank=True, max_length=150, verbose_name='Business Category')),
                ('departemen', models.CharField(blank=True, max_length=200, verbose_name='Department')),
                ('owner', models.TextField(blank=True, verbose_name='Owner')),
                ('pic_operational', models.CharField(blank=True, max_length=200, verbose_name='PIC Operational')),
                ('monitoring', models.CharField(blank=True, max_length=50, verbose_name='Monitoring')),
                ('site', models.CharField(blank=True, max_length=20, verbose_name='Site')),
                ('installed_by', models.CharField(blank=True, max_length=100, verbose_name='Installed By')),
                ('size_mountpoint', models.CharField(blank=True, max_length=50, verbose_name='Size Mountpoint')),
                ('size_database', models.CharField(blank=True, max_length=200, verbose_name='Size Database')),
            ],
            options={
                'verbose_name': 'Database Inventory',
                'verbose_name_plural': 'Database Inventories',
                'ordering': ['no'],
            },
        ),
    ]
