# Generated by Django 5.2.10 on 2026-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinventory',
            name='size_database',
            field=models.TextField(blank=True, verbose_name='Size Database'),
        ),
    ]
