# Generated by Django 5.2.10 on 2026-01-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_size_database_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinventory',
            name='is_dismantled',
            field=models.BooleanField(default=False, verbose_name='Dismantled'),
        ),
    ]
